name: Build and Push Docker Image

on:
  push:
    branches:
      - develop

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      # - name: Log in to Docker Hub
      #   uses: docker/login-action@v3
      #   with:
      #     username: ${{ secrets.DOCKERHUB_USERNAME }}
      #     password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Prepare apps.json
        run: |
          echo "github.actor=$(github.actor)"

      - name: Clone frappe_docker Template
        run: git clone --depth 1 https://github.com/frappe/frappe_docker

      - name: Prepare Apps JSON
        id: apps-json
        run: |
          # Construct your array containing core apps + prerequisites + your app
          JSON_CONTENT='[
            {"url": "https://github.com/frappe/erpnext", "branch": "version-15"},
            {"url": "https://github.com/frappe/payments", "branch": "version-15"},
            {"url": "https://github.com/resilient-tech/india_compliance", "branch": "version-15"},
            {"url": "https://github.com/frappe/hrms", "branch": "version-15"},
            {"url": "https://github.com/TheWellNest-in/wellnest-app", "branch": "develop"}
          ]'
          echo "b64=$(echo -n "$JSON_CONTENT" | base64 -w 0)" >> $GITHUB_OUTPUT

      - name: Build and Push Monolithic Image
        uses: docker/build-push-action@v5
        with:
          context: ./frappe_docker
          file: ./frappe_docker/images/layered/Containerfile
          push: true
          tags: ghcr.io/${{ github.repository_owner }}/careyogi-erpnext:latest,docker.io/${{ secrets.DOCKERHUB_USERNAME }}/careyogi-erpnext:latest
          build-args: |
            FRAPPE_BRANCH=version-15
            PYTHON_VERSION=3.11
            NODE_VERSION=18.18.2
            APPS_JSON_BASE64=${{ steps.apps-json.outputs.b64 }}
